config/routes.rb
Rails.application.routes.draw do
  resources :users
  root 'home#index'

  resources :users, only: [:create, :destroy, :edit]
  get '/club', to: 'users#index'
  get '/register', to: 'users#new'

  delete '/logout', to: 'sessions#destroy'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true, uniqueness: true
  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    if session[:user_id]
      current_user ||= User.find(session[:user_id])
    else
      current_user = nil
    end
    return current_user
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    if current_user
      redirect_to '/club', notice: "Vous êtes déjà connecté(e)!"
    end
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = "Connexion réussie !"
      redirect_to '/club'
    else
      flash[:alert] = "L'email ou le mot de passe est incorrect."
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Déconnexion réussie !"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    if current_user
      @users = User.all
    else
      flash[:alert] = "Vous n'êtes pas connecté(e)"
      redirect_to '/login'
    end
  end

  def show
    unless current_user
      render :file => "#{Rails.root}/public/403.html"
    end
  end

  def new
    if current_user
      redirect_to '/club', notice: "Vous êtes déjà connecté(e)!"
    else
      @user = User.new
    end
  end

  def edit
    unless current_user && @user.id == current_user.id
      render :file => "#{Rails.root}/public/403.html"
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:alert] = nil
      redirect_to '/login', notice: "Inscription réussie !"
    else
      render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to '/club'
    else
      render :edit
    end
  end

  def destroy
    if current_user && @user.id == current_user.id
      @user.destroy
      session[:user_id] = nil
      redirect_to root_url, notice: "Compte supprimé !"
    else
      render :file => "#{Rails.root}/public/403.html", layout: false, status: :not_found
    end
  end

  private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<br>
<div align="center"
  <% if flash[:notice] %>
    <div class="alert alert-success" role="alert"><%= flash[:notice] %></div>
  <% else %>
    <br>
  <% end %>
</div>
<div align="center" style="margin-top:150px">
  <h2 style="color:  #f1f1f1">Bienvenue sur le club de Strasbourg ! 🕺</h2>
  <br>
  <div id="buttons-home">
    <%= link_to "Inscription", register_url, class: "btn btn-success" %>
    <div style="padding-left: 10px">
      <%= link_to "Connexion", login_url, class: "btn btn-primary" %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gossip</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.2/css/all.css" integrity="sha384-/rXc/GQVaYpyDdyxK+ecHPVYJSN9bmVFBvjA/9eOB+pb3F2w2N6fc5qB9Ew5yIns" crossorigin="anonymous">

    <!--NAVBAR -->
    <nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark">
      <a class="navbar-brand" href="/"><img src="http://image.noelshack.com/fichiers/2018/45/1/1541413576-design-2.png" alt="Strasbourg Club" width="200" height="80"></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="nav navbar-nav">
          <li class="nav-item">
            <a class="nav-link" style="color:  #f1f1f1" href="/">Accueil</a>
          </li>
          <li class="nav-item">
            <% if current_user %>
              <a class="nav-link" style="color:  #f1f1f1" href="/club">Le club</a>
            <% end %>
          </li>
        </ul>
      </div>

      <!-- NAVBAR RIGHT -->
      <div class="navbar-right" id="nav-at-right">
        <a class="nav-link" style="color: #f1f1f1"><%= current_user ? "Connecté(e) en tant que : #{current_user.first_name} #{current_user.last_name}" : "" %></a>
        <% if current_user %>
          <div class="button-right">
            <%= link_to "Log Out", logout_url, class: "btn btn-danger", method: :delete %>
          </div>
        <% else %>
          <%= link_to "Inscription", register_url, class: "btn btn-success" %>
          <div style="padding-left: 20px">
            <%= link_to "Connexion", login_url, class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
    </nav>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= bootstrap_form_with(model: user, local: true) do |form| %>
  <div id="user_form">
      <div class="field">
        <%= form.text_field :first_name, placeholder: "Prénom", label: "Prénom", label_class: "user_label"%>
      </div>

      <div class="field">
        <%= form.text_field :last_name, placeholder: "Nom de famille", label: "Nom de famille", label_class: "user_label"%>
      </div>

      <div class="field">
        <%= form.text_field :email, placeholder: "Adresse Email", label: "Adresse Email", label_class: "user_label"%>
      </div>

      <div class="field">
        <%= form.password_field :password, placeholder: "Mot de passe", label: "Mot de passe", label_class: "user_label" %>
      </div>

      <div class="field">
        <%= form.password_field :password_confirmation, placeholder: "Mot de passe", label: "Confirmation du mot de passe", label_class: "user_label" %>
      </div>

      <div class="actions">
        <%= form.submit "Confirmer", class: "btn btn-success" %>
      </div>
      <br>
    </div>
<% end %>

app/views/users/edit.html.erb
<div align="center" style="margin-top:60px">

  <h1 style="color: #f1f1f1">Modifier l'utilisateur</h1>

  <%= render 'form', user: @user %>
</div>

app/views/users/index.html.erb
<br>
<div align="center">

  <% if flash[:notice] %>
    <div class="alert alert-success" role="alert"><%= flash[:notice] %></div>
    <% else %>
      <br>
  <% end %>

  <br>
  <h2 style="color:  #f1f1f1">Le carré VIP</h2>
  <br>
  <br>

  <table class="table table-striped table-dark">
    <thead>
      <tr>
        <th scope="col">Numéro</th>
        <th scope="col">Prénom</th>
        <th scope="col">Nom</th>
        <th scope="col">Adresse Email</th>
        <th colspan="4" scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <th scope="row"><%= user.id %></th>
          <td><%= user.first_name %></td>
          <td><%= user.last_name %></td>
          <td><%= user.email %></td>
          <td class="tr-action"><%= link_to 'Voir le profil', user, class: "btn btn-primary"%>
          <% if current_user.id == user.id %>
            <%= link_to 'Modifier', edit_user_path(user), class: "btn btn-success"%>
            <%= link_to 'Supprimer', user, method: :delete, class: "btn btn-danger", data: { confirm: 'Êtes-vous sûr ?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>
</div>

app/views/users/new.html.erb
<div align="center" style="margin-top:60px">

  <h1 style="color: #f1f1f1">Nouvel utilisateur</h1>

  <%= render 'form', user: @user %>
</div>

app/views/users/show.html.erb
<br>
<br>
<div align="center" style="margin-top:100px">
  <div class="card text-center" style="width: 30rem;">
    <div class="card-header">
      <h1><%= "#{@user.first_name} #{@user.last_name}" %></h1>
    </div>
    <div class="card-body">
        <h4><p class="card-text"><%= "Email : #{@user.email}" %></p></h4>
        <br>
        <p class="card-text"><%= "Date de création : #{@user.created_at}" %></p>
        <p class="card-text"><%= "Dernière mise à jour : #{@user.updated_at}" %></p>
        <br>
        <a href="/users" class="btn btn-primary">Retourner au club</a>
    </div>
  </div>
  <br>
</div>